# Backpropagation
in Neural Network


In [1]:
import numpy as np
import pandas as pd

df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa', 'profile_score', 'lpa'])

In [3]:
X = df.iloc[:,0:2]
y = df.iloc[:,-1]

In [5]:
def initialize_parameters(layer_dims):
      
  np.random.seed(3)
  parameters = {}
  L = len(layer_dims)         

  for l in range(1, L):

    parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
    parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
      

  return parameters

In [6]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [7]:
def linear_forward(A_prev, W, b):
      
  Z = np.dot(W.T, A_prev) + b
  
  return Z

In [8]:
# Forward Progation
def L_layer_forward(X, parameters):
    
  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    #print("A"+str(l-1)+": ", A_prev)
    #print("W"+str(l)+": ", Wl)
    #print("b"+str(l)+": ", bl)
    #print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    #print("A"+str(l)+": ", A)
    #print("**"*20)
          
  return A,A_prev

In [9]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [10]:
y_hat = y_hat[0][0]

In [11]:
A1

array([[1.6],
       [1.6]])

In [13]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[3][0]

y_hat,A1 = L_layer_forward(X, parameters)

In [17]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001 * 2 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0]*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][0][0])

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0]*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001 * 2 * (y - y_hat)*parameters['W2'][1][0])

In [18]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

parameters

{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [19]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 5

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['lpa']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  25.321744156025517
Epoch -  2 Loss -  18.320004165722047
Epoch -  3 Loss -  9.473661050729628
Epoch -  4 Loss -  3.2520938634031613
Epoch -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

# Using Keras

In [28]:
import tensorflow
from tensorflow import keras
from  tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
model = Sequential()
model.add(Dense(2,activation ='linear',input_dim =2))
model.add(Dense(1,activation ='linear'))



In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 2)                 6         
                                                                 
 dense_2 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9 (36.00 Byte)
Trainable params: 9 (36.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [24]:
model.get_weights()

[array([[-0.8329072,  0.5477536],
        [ 1.2123326,  1.0553113]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.7678491 ],
        [-0.88008416]], dtype=float32),
 array([0.], dtype=float32)]

In [25]:
new_weights =[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),
              np.array([0.,0.],dtype=np.float32),
              np.array([[0.1],[0.1]],dtype=np.float32),
              np.array([0.],dtype=np.float32)]

In [26]:
model.set_weights(new_weights)

In [29]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [30]:
model.fit(df.iloc[:,0:2].values,df.iloc[:,-1].values,epochs =75,verbose=1,batch_size=1)

Epoch 1/75

4/4 [==============================] - 1s 4ms/step - loss: 35.0153
Epoch 2/75
4/4 [==============================] - 0s 8ms/step - loss: 34.0890
Epoch 3/75
4/4 [==============================] - 0s 5ms/step - loss: 33.1529
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 32.1530
Epoch 5/75
4/4 [==============================] - 0s 5ms/step - loss: 31.2677
Epoch 6/75
4/4 [==============================] - 0s 2ms/step - loss: 30.3094
Epoch 7/75
4/4 [==============================] - 0s 7ms/step - loss: 29.4585
Epoch 8/75
4/4 [==============================] - 0s 3ms/step - loss: 28.6275
Epoch 9/75
4/4 [==============================] - 0s 7ms/step - loss: 27.7671
Epoch 10/75
4/4 [==============================] - 0s 6ms/step - loss: 27.0022
Epoch 11/75
4/4 [==============================] - 0s 16ms/step - loss: 26.2206
Epoch 12/75
4/4 [==============================] - 0s 6ms/step - loss: 25.5249
Epoch 13/75
4/4 [==============================] - 0s 6ms/s